// RPS Clinical Reference — content extracted from the user's source documents.
// Source: "Bates' Integrated Core + Cluster Physical Examination Framework",
// "Appendix A – Illness Scripts", abbreviations list, and PE modifications list.

export const CORE_PE = [
  {
    id: "core-1", section: "Universal",
    tasks: [
      { task: "Washes hands BEFORE exam", full: "Student washed hands AT ANY TIME BEFORE the physical with your full knowledge; using an instant hand sanitizer (e.g., Purell) IS also acceptable.", partial: "Student did not sanitize hands before the physical exam but did so after entering the room and before leaving, or made vague reference to prior handwashing without visible evidence." },
      { task: "Observes proper draping", full: "Student used the drape effectively, exposing only one body part at a time. One prompt allowed.", partial: "More than one prompt OR SP must adjust own drape → lower score." },
      { task: "Washes hands AFTER exam", full: "Student washed hands AFTER the physical with your full knowledge; instant sanitizer acceptable.", partial: "Not performed." },
    ],
  },
  {
    id: "core-2", section: "General Appearance & Vital Signs",
    tasks: [
      { task: "Observes general appearance", full: "Student observes the patient's overall appearance including distress, posture, mental status, color, and general demeanor.", partial: "Brief glance OR insufficient assessment OR omission of key features." },
      { task: "Assesses orientation (person, place, time)", full: "Student asks at least where the SP is (place) AND what time of day or date it is (time) AND asks the SP to state their own name (person). ALL ITEMS needed for full credit.", partial: "Asked only one or two of the three orientation domains OR used closed-ended or leading questions." },
      { task: "Measures blood pressure", full: "Cuff placed on right OR left arm AND strands positioned toward the hands; no gown caught under cuff; correct on first try without causing undue pain.", partial: "Minor technique issues OR had to repeat due to avoidable error OR caused minor discomfort." },
      { task: "Measures heart rate (pulse)", full: "Student used fingers and NOT thumb AND placed fingers on radial side of wrist; MUST count ≥15 seconds.", partial: "Counted <15 seconds OR used thumb OR improper location." },
      { task: "Measures respiratory rate", full: "Student quietly observes the patient's breathing for at least 15 seconds and counts respirations.", partial: "Observed <15 seconds OR estimated without counting OR did not clearly observe movement." },
    ],
  },
  {
    id: "core-3", section: "HEENT + Cranial Nerve Screen",
    tasks: [
      { task: "Inspects external eye and lid", full: "Student inspected BOTH eyes AND used a light source to examine the external eye and eyelid for abnormalities.", partial: "Inspected only one eye OR did not use a light source OR examined too quickly to assess for abnormalities." },
      { task: "Assesses pupillary light reflex (CN II/III)", full: "Using a light source, student shines the light into the SP's eye, one eye at a time, observing for pupillary constriction.", partial: "Shined light into only one eye OR did not check consensual response OR used inadequate light/technique." },
      { task: "Inspects oropharynx and dentition", full: "Student asked SP to open mouth, stick out tongue AND used a light source and tongue depressor (without causing gag).", partial: "Omitted tongue depressor OR failed to use a light source OR did not ask SP to stick out tongue." },
      { task: "Palpates cervical lymph nodes", full: "Student palpated at minimum THREE areas: submental, submandibular, parotid, postauricular, occipital, anterior cervical, posterior cervical, deep cervical, and/or supraclavicular.", partial: "Only 1–2 areas OR incorrect/superficial palpation." },
    ],
  },
  {
    id: "core-4", section: "Cardiac",
    tasks: [
      { task: "Palpates chest for cardiac PMI", full: "Student palpated using fingers or palm along the left nipple area with the SP lying or sitting (adjusting for breast tissue with permission when needed).", partial: "Incorrect location (too medial/high), did not adjust for breast tissue, or technique that would not reliably detect the PMI." },
      { task: "Auscultates heart in 4 areas", full: "Student listened in the left AND right upper breastbone borders AND left lower breastbone border AND along the nipple area.", partial: "Only 2–3 locations OR auscultated over clothing OR incorrect apex placement." },
    ],
  },
  {
    id: "core-5", section: "Pulmonary",
    tasks: [
      { task: "Percusses posterior chest (3 levels)", full: "Student percusses and COMPARES BOTH SIDES (side to side) AND checks at least 3 levels.", partial: "Fewer than 3 levels OR only one side OR failed to alternate sides OR incorrect technique." },
      { task: "Auscultates posterior chest (3 levels)", full: "Student listens side-to-side on BOTH sides AND checks ≥3 levels; MUST instruct deep breathing; MUST wait for exhale before moving.", partial: "Fewer than 3 levels OR one side OR unclear breath instruction OR moves without waiting for exhale." },
      { task: "Auscultates anterior chest (2 levels)", full: "Student listens side to side on BOTH sides AND checks at least 2 levels; MUST instruct deep breaths.", partial: "Only one side OR fewer than 2 levels OR no breath instruction." },
    ],
  },
  {
    id: "core-6", section: "Abdomen",
    tasks: [
      { task: "Inspects abdomen", full: "Student visually inspects for contour, symmetry, skin changes, pulsations, or scars BEFORE any other abdominal maneuvers.", partial: "Inspects AFTER other maneuvers OR brief/incomplete inspection." },
      { task: "Auscultates abdomen before palpation", full: "Student listened at any quadrant prior to palpating or percussing. MUST be done first.", partial: "Auscultated after beginning palpation/percussion OR too briefly/unclear location to assess bowel sounds." },
      { task: "Light abdominal palpation (all 4 quadrants)", full: "Student used light force with one or two hands AND palpated all 4 quadrants.", partial: "Moderate/deep pressure OR 1–3 quadrants only." },
      { task: "Deep abdominal palpation (all 4 quadrants)", full: "Student used deep downward force with one or two hands AND palpated all 4 quadrants.", partial: "Only light pressure OR wrong technique OR 1–3 quadrants only." },
    ],
  },
  {
    id: "core-7", section: "Vascular",
    tasks: [
      { task: "Palpates posterior tibial pulses (bilateral)", full: "Student examines BOTH sides and feels for pulse along medial aspect of ankles.", partial: "Only one side OR incorrect location OR improper pressure." },
      { task: "Palpates dorsalis pedis pulses (bilateral)", full: "Student examines BOTH sides and feels for pulse along top of feet.", partial: "Only one side OR incorrect location OR improper pressure." },
      { task: "Palpates lower extremity for edema", full: "Student palpates BOTH lower anterior legs directly on shin area over bone.", partial: "One leg only OR palpates non-bone areas OR superficial pressure." },
    ],
  },
  {
    id: "core-8", section: "Neurologic",
    tasks: [
      { task: "Gross UE motor strength (≥2 groups each arm)", full: "Student assessed AT LEAST TWO muscle groups in BOTH upper extremities AGAINST RESISTANCE.", partial: "Fewer than two groups OR passive movement OR weak resistance." },
      { task: "Gross LE motor strength (≥2 groups each leg)", full: "Student assessed AT LEAST TWO muscle groups in BOTH lower extremities AGAINST RESISTANCE.", partial: "Fewer than two groups OR passive movement OR weak resistance." },
      { task: "Assesses gait", full: "Student asks patient to walk and assesses natural gait.", partial: "Asked to walk but does not adequately observe gait." },
    ],
  },
];

const T = (task, full, partial) => ({ task, full, partial });

export const CLUSTERS = [
  {
    id: "cardiac", name: "Cardiac", color: "#0073A2",
    blurb: "Rapidly evaluates perfusion, hemodynamic stability, and signs of structural heart disease. Core maneuvers establish a cardiovascular baseline; cluster maneuvers are added when history or findings suggest ischemia, volume overload, dysrhythmia, or valvular pathology.",
    presentations: ["Chest pain", "Palpitations", "Syncope (cardiac subtype)", "Edema (CHF)"],
    coreTasks: ["Observes general appearance", "Measures blood pressure", "Measures pulse (rate)", "Measures respiratory rate", "Palpates chest for cardiac PMI", "Auscultates chest in 4 areas", "Palpates lower extremities for edema", "Palpates dorsalis pedis pulses", "Palpates posterior tibial pulses", "Auscultates posterior lungs (3 levels)", "Auscultates anterior lungs (2 levels)"],
    clusterTasks: [
      T("Auscultates THEN palpates carotids (one side at a time)", "Did BOTH auscultation and palpation of the carotids one at a time AND used only the fingers (NOT thumb). MUST auscultate before palpation.", "Examined only one carotid OR used thumbs OR failed to auscultate before palpation OR performed both sides simultaneously (unsafe)."),
      T("Estimates jugular venous pressure (JVP)", "Positions patient at 30–45°, uses tangential lighting, inspects the right neck, identifies the highest jugular pulsation, and estimates vertical distance from the sternal angle in cm.", "Incorrect angle, overhead/no lighting, wrong area, or inaccurate vertical-height estimate."),
      T("Auscultates in left lateral decubitus (mitral stenosis)", "Asks patient to roll onto left side, uses the bell at the apex, listens silently for 5 seconds.", "Skips position, uses wrong tool/location, or does not listen silently for 5 seconds."),
      T("Auscultates leaning forward (aortic regurgitation)", "Asks patient to sit up, exhale, and lean forward; uses the diaphragm at the LSB or base; listens silently 5 seconds.", "Misses a step (no lean/exhale), wrong tool/location, or doesn't listen silently 5 seconds."),
    ],
    addOns: [],
  },
  {
    id: "pulmonary", name: "Pulmonary", color: "#0E3692",
    blurb: "A structured sequence assessing ventilation and gas exchange. Core maneuvers apply to all pulmonary complaints; cluster maneuvers are selected by symptom pattern and suspicion for consolidation, effusion, or obstruction.",
    presentations: ["Shortness of breath", "Cough", "Hemoptysis", "Wheezing", "Pleuritic chest pain"],
    coreTasks: ["Observes general appearance", "Measures respiratory rate", "Measures pulse (rate)", "Measures blood pressure", "Auscultates posterior chest (3 levels)", "Auscultates anterior chest (2 levels)", "Auscultates chest in 4 areas", "Palpates lower extremities for edema"],
    clusterTasks: [
      T("Assesses posterior chest expansion", "Palpates BOTH sides using sides of hands/palms AND checks ≥1 level over posterior lungs, testing both sides simultaneously. MUST ask for a deep breath.", "Only one side OR no simultaneous comparison OR omitted breath instruction OR poor hand positioning."),
      T("Posterior chest tactile fremitus", "Palpates and COMPARES BOTH SIDES (while SP repeats 'ninety-nine' or 'toy boat') AND checks ≥3 levels in the back.", "Fewer than 3 levels OR one side OR omitted spoken phrase OR improper palms without comparison."),
      T("Percusses posterior chest", "Percusses and COMPARES BOTH SIDES (side to side) AND checks ≥3 levels.", "Fewer than 3 levels OR one side OR failed to alternate OR incorrect technique."),
      T("Assesses for egophony", "Instructs patient to say 'ee' while auscultating ≥3 posterior fields per side with the diaphragm, listening for 'ee'→'ay' change.", "Fewer than 3 fields per side OR unclear instruction OR no diaphragm."),
      T("Assesses for whispered pectoriloquy", "Instructs patient to whisper '1-2-3' or 'toy boat' while auscultating ≥3 posterior fields per side with the diaphragm.", "Fewer than 3 fields per side OR unclear instruction OR no diaphragm."),
      T("Assesses for CVA tenderness (pulm vs renal overlap)", "Locates the costovertebral angle bilaterally, places one flat hand over the angle, percusses with a closed fist, and asks about pain after each side.", "No flat hand, wrong location, only one side, or struck too forcefully/lightly."),
    ],
    addOns: [
      T("Inspects for accessory muscle use", "Inspects anterior/lateral chest for SCM, scalene, intercostal retractions during normal breathing; identifies increased work of breathing.", "Glances without clearly assessing, or doesn't comment on presence/absence of increased work of breathing."),
      T("Wheezing with forced expiration", "Instructs full inhalation then forceful exhalation while auscultating anterior/posterior fields with the diaphragm for wheezing.", "No forceful exhalation, one area only, bell instead of diaphragm, or listens too briefly."),
      T("Measures oxygen saturation", "Applies pulse oximeter correctly, ensures sensor placement, waits for a stable reading, states SpO₂ and pulse.", "Incorrect placement, no stable reading, unconfirmed value, or misinterpretation."),
      T("Measures peak flow (asthma)", "Sets meter to zero, instructs maximal inhalation and tight lip seal, blows out hard/fast, repeats ×3, records highest value.", "No reset, unclear instructions, air leaks, fewer than 3 attempts, or fails to record highest value."),
    ],
  },
  {
    id: "gi", name: "GI / Abdominal", color: "#68357C",
    blurb: "A structured abdominal exam beginning with inspection, then auscultation and palpation. Core maneuvers apply to all abdominal complaints; cluster maneuvers are added by quadrant localization and suspicion for inflammatory, obstructive, or visceral pathology.",
    presentations: ["Abdominal pain (RUQ, RLQ, LLQ, epigastric)", "Nausea / vomiting", "Diarrhea", "Constipation", "GI bleeding (melena, hematochezia, hematemesis)"],
    coreTasks: ["Observes general appearance", "Measures blood pressure", "Measures pulse (rate)", "Measures respiratory rate", "Inspects the abdomen", "Auscultates abdomen prior to palpation", "Light abdominal palpation (all 4 quadrants)", "Deep abdominal palpation (all 4 quadrants)"],
    clusterTasks: [
      T("Palpates liver edge", "Palpates just below the right rib cage, coordinated with the patient's inspiration.", "Too high/lateral, shallow pressure, or not coordinated with inspiration."),
      T("Palpates spleen", "Full credit by any of: (1) supine bimanual exam with one hand posterior and one anterior at the left lower rib cage; (2) hooking technique under the left costal margin; or (3) right-lateral-decubitus palpation under the left costal margin.", "Palpates near left costal margin without a validated approach, omits deep inspiration, uses one hand, or uses an ineffective maneuver."),
      T("Performs Murphy's sign", "Palpates just below the right costal margin at the MCL, instructs a deep breath, observes for discomfort or inspiratory pause.", "Wrong location, pressure not coordinated with inspiration, or unclear breathing instructions."),
      T("McBurney's point tenderness & rebound", "Locates McBurney's point (1/3 from ASIS to umbilicus), applies firm pressure, releases abruptly, asks about pain.", "Wrong location, slow/incomplete release, or unclear instructions."),
      T("Assesses for rebound tenderness", "Presses gently but firmly into the lower abdomen, quickly releases, asks if pain worsens on release.", "Wrong location, slow/incomplete release, or unclear instructions."),
      T("Performs Rovsing's sign", "Presses into the LLQ and asks whether pain is felt in the RLQ.", "Asks about local pain only, presses wrong quadrant, or too briefly/gently."),
      T("Performs psoas sign", "Either raises the right leg against resistance, OR passively extends the right leg in left lateral decubitus, asking about RLQ pain.", "Poor technique (wrong leg/position) or asks about general discomfort rather than RLQ pain."),
      T("Performs obturator sign", "Supine: flexes right hip and knee to 90°, gently rotates the leg internally and externally at the hip, asks about RLQ pain.", "Improper flexion, minimal/too-fast rotation, rotates at knee, tests one movement, or fails to ask about RLQ pain."),
      T("Assesses for CVA tenderness", "Locates the CVA bilaterally, places one flat hand over the angle, percusses with a closed fist, asks about pain after each side.", "No flat hand, wrong location, one side only, or struck too forcefully/lightly."),
    ],
    addOns: [
      T("Performs rectal exam", "Explains, drapes, positions (LLD or standing leaning forward), lubricates, inserts gently, palpates circumferentially for masses/tenderness/tone/stool/blood, inspects glove.", "Incomplete explanation/draping, wrong position, abrupt/unlubricated insertion, incomplete palpation, or fails to inspect glove."),
      T("Stool guaiac test (FOBT)", "Applies small stool sample to the card, adds developer, waits, interprets color change accurately.", "Incorrect sample, no developer, insufficient wait, or misinterpretation."),
      T("Performs hernia exam", "Inspects groin, asks patient to stand, palpates the inguinal canal, asks patient to cough/bear down feeling for an impulse.", "Inspects without palpating, wrong location, omits cough/strain, or poor draping/explanation."),
      T("Performs Carnett's sign", "Identifies maximal tenderness, maintains pressure, asks patient to lift head/shoulders (or raise legs); notes increased (wall) vs decreased (intra-abdominal) tenderness.", "Doesn't maintain pressure, unclear instructions, fails to observe response, or misinterprets."),
      T("Performs pelvic exam (if indicated)", "Explains, drapes, lithotomy positioning, inspects external genitalia, speculum exam, bimanual exam (uterus, adnexa, CMT), maintains comfort and communicates.", "Inadequate explanation/draping, improper speculum, no cervix visualization, incomplete bimanual, or fails to monitor comfort."),
    ],
  },
  {
    id: "neuro", name: "Neuro-Vestibular", color: "#58595B",
    blurb: "Screens mental status, cranial nerves, strength, and gait. Core maneuvers give a rapid neurologic baseline; cluster maneuvers help distinguish central from peripheral processes and support lesion localization.",
    presentations: ["Dizziness", "Vertigo", "Syncope", "Weakness", "Balance disorders"],
    coreTasks: ["Observes general appearance", "Measures blood pressure", "Measures pulse (rate)", "Measures respiratory rate", "Pupillary light reflex (CN II/III)", "Extraocular movements (CN III/IV/VI)", "Facial symmetry (CN VII)", "Gross hearing (CN VIII)", "Tongue position/movement (CN XII)", "UE motor strength (≥2 groups/arm)", "LE motor strength (≥2 groups/leg)", "Natural gait"],
    clusterTasks: [
      T("UE reflexes: biceps", "Examines BOTH biceps reflexes with the arm supported on the student's forearm or the patient's thigh.", "One side only, incorrect support, or strikes wrong location."),
      T("UE reflexes: triceps", "Examines BOTH triceps reflexes with the arm supported, striking the correct tendon.", "One side only, inadequate support, or strikes above/below tendon."),
      T("Knee reflexes (patellar)", "Examines BOTH patellar reflexes with legs freely dangling, striking the tendon correctly.", "One side only, legs not dangling, or misses tendon."),
      T("Ankle reflexes (Achilles)", "Examines BOTH sides and lifts/supports the foot before striking the Achilles tendon.", "One side only, no foot support, or strikes outside tendon."),
      T("Plantar reflex (Babinski)", "Examines BOTH sides, firm stroke in a 'C' or 'L' along the lateral foot and across the great toe.", "One foot only, incorrect stroke, socks on, or too light/forceful."),
      T("Tests station (Romberg)", "Patient stands feet together, eyes closed; observes for sway or loss of balance.", "Feet apart, no eye closure, or unclear instructions."),
      T("Cerebellar function", "Rapid alternating movements, finger-to-nose, or heel-to-shin — performed on both sides.", "One side only, unclear instructions, or too few repetitions."),
      T("Vibration sense (UE + LE)", "Vibrating tuning fork on a bony prominence of one finger and one toe; asks when vibration starts and stops.", "One limb only, fork on soft tissue, or no start/stop verification."),
      T("Proprioception (UE + LE)", "Holds the sides of a finger and toe, moves up/down with eyes closed, asks for direction.", "One limb only, incorrect grip (top/bottom), or unclear movement/questioning."),
      T("Toe walk, heel walk, tandem gait", "Asks patient to (1) walk on toes, (2) walk on heels, (3) tandem walk heel-to-toe in a straight line.", "Only one/two components, unclear instructions, or inadequate observation."),
      T("Nuchal rigidity (when indicated)", "Gently lifts the head, bringing chin toward chest, observing for stiffness/resistance.", "No head support, too abrupt, or chin not brought fully to chest."),
      T("Kernig test (when indicated)", "Flexes hip and knee to 90°, then straightens the leg observing for pain/resistance.", "One side only, hip not held at 90°, or extends too quickly/incompletely."),
      T("Brudzinski test (when indicated)", "Lifts the head toward the chest, observes for involuntary hip/knee flexion.", "Lifts too quickly, fails to observe legs, or misses hip/knee response."),
      T("Dix–Hallpike (gold standard for BPPV)", "Turns head 45° to one side, supports head/shoulders, moves rapidly sitting→supine with head extended below the table; observes eyes for nystagmus and asks about vertigo; repeats opposite side.", "Wrong head position, too slow/no extension, no eye observation, no vertigo query, or only one side."),
      T("HINTS exam (acute vestibular syndrome)", "Performs head-impulse (corrective saccades), nystagmus in primary/left/right gaze, and alternating cover-uncover for skew; interprets central vs peripheral.", "Fewer than all three components, incorrect technique, poor instruction, or no interpretation."),
      T("Assesses nystagmus", "Patient looks straight then left/right/up/down while observing for spontaneous, gaze-evoked, or positional nystagmus; notes direction, fatigability, symmetry.", "Primary gaze only, no multi-direction assessment, brief observation, or no comment."),
      T("Orthostatic vital signs", "Measures BP and pulse supine (≥3 min), then standing at 1 and 3 min, assessing for orthostatic drop or compensatory pulse rise.", "Measured once, no wait, no pulse, or inconsistent timing."),
      T("Pronator drift (UMN sign)", "Patient holds both arms forward, palms up, eyes closed 10–20 s; observes for pronation/drift/asymmetry.", "Wrong arm position, no eye closure, too short, or fails to identify subtle drift."),
      T("Light-touch sensory exam", "Lightly touches symmetric UE/LE areas, comparing right and left and asking if sensation is the same.", "One limb only, inconsistent touch, or no side comparison."),
      T("Pinprick sensory exam (if allowed)", "Uses a disposable pin/neurotip on symmetric UE/LE locations, comparing sides and asking about sharpness/symmetry.", "One location/limb only, inconsistent pressure, no comparison, or no query."),
    ],
    addOns: [],
  },
  {
    id: "msk", name: "Musculoskeletal", color: "#0E3692",
    blurb: "Focused evaluation of movement, symmetry, and localized tenderness. Core maneuvers form a global MSK screen; cluster maneuvers are selected by the joint or region involved (Inspect, Palpate, ROM, Special — IPROMS).",
    presentations: ["Joint pain", "Limb pain or swelling", "Shoulder / knee / hip / wrist / ankle pain", "Back pain", "Neck pain", "Gait disturbance due to MSK pain"],
    coreTasks: ["Observes general appearance", "Measures blood pressure", "Measures pulse (rate)", "Inspects the affected joint", "Palpates the affected joint", "Active & passive ROM of the affected joint", "Assesses gait (if LE involvement)", "Palpates LE for edema (if swelling)"],
    clusterTasks: [
      T("SHOULDER — Inspects joint", "Visually inspects both shoulders, comparing sides, patient seated/standing with both shoulders exposed.", "One shoulder, through clothing, or cursory glance."),
      T("SHOULDER — Palpates joint", "Palpates clavicle, AC joint, bicipital groove, scapular spine bilaterally, asking about tenderness.", "Fewer than two landmarks, one shoulder, or poor technique."),
      T("SHOULDER — ROM flexion/extension", "Raises both arms forward and overhead (flexion), then extends behind the body.", "One movement or one arm only."),
      T("SHOULDER — ROM abduction/adduction", "Lifts both arms out to the side and overhead (abduction), then across the body (adduction).", "One direction, one arm, or allows compensation."),
      T("SHOULDER — ROM internal/external rotation", "Internal rotation (hand behind back) and external rotation (arms abducted 90°, elbows bent, forearms rotated back).", "One direction/arm, unclear instruction, or improper positioning."),
      T("SHOULDER — Drop arm test", "Lifts the arm to shoulder level and asks the patient to slowly lower it, observing for control.", "One side, unclear instruction, or doesn't watch descent."),
      T("SHOULDER — Neer test", "Gently lifts the straight arm forward/upward, palm down, while stabilizing the shoulder.", "One arm, bent elbow, or fails to stabilize."),
      T("SHOULDER — Modified Hawkins test", "Lifts arm to shoulder level, bends elbow, rotates forearm downward while stabilizing.", "Wrong position, one side, or moves too quickly."),
      T("SHOULDER — Empty can test", "Arms to shoulder height angled forward, thumbs down, resists downward pressure.", "Improper hand position, one side, or inadequate resistance."),
      T("KNEE — Inspects joint", "Inspects both knees, patient seated/standing, comparing sides.", "One knee or no comparison."),
      T("KNEE — Palpates joint", "Palpates both knees around patella, joint lines, and soft tissue.", "One knee or misses key areas."),
      T("KNEE — ROM flexion/extension", "Bends (flex) and straightens (extend) the knee fully, both sides.", "One movement or one leg."),
      T("KNEE — Lachman / anterior drawer", "Performs Lachman or anterior drawer on both knees, stabilizing and pulling the tibia forward.", "Improper stabilization, one side, or wrong direction of pull."),
      T("KNEE — Posterior drawer", "Flexes knee to 90°, stabilizes, pushes the tibia posteriorly, both sides.", "One side or incorrect hand placement."),
      T("KNEE — Varus (LCL) stress", "Applies inward pressure to the lower leg while stabilizing the thigh.", "One side or incorrect hand placement."),
      T("KNEE — Valgus (MCL) stress", "Applies outward pressure on the lower leg while stabilizing the thigh.", "One side or misdirected pressure."),
      T("HIP — Inspects joint", "Inspects bilateral hip area, patient standing or supine.", "One side or poor positioning."),
      T("HIP — Palpates joint", "Palpates anterior hip joint region and greater trochanter bilaterally.", "One side or incorrect structures."),
      T("HIP — ROM flexion/extension", "Bends forward to touch toes (flexion) and leans back (extension) with support.", "One direction or poor instruction."),
      T("HIP — ROM abduction/adduction", "Moves leg laterally away (abduction) and across midline (adduction).", "One direction or one leg."),
      T("HIP — ROM internal/external rotation", "Rotates the lower leg inward and outward while seated, bilaterally.", "One side or unclear instructions."),
      T("SPINE — Inspects lumbar spine", "Visually inspects the lower back while the patient stands upright.", "Poor visibility or clothing obstructs view."),
      T("SPINE — Palpates vertebrae", "Palpates the entire spine C1→coccyx, asking about tenderness.", "Partial spine or poor explanation/draping."),
      T("SPINE — Palpates paraspinal muscles", "Palpates paraspinals bilaterally C1→coccyx, asking about tenderness.", "Limited area or inconsistent pressure."),
      T("SPINE — ROM flexion/extension", "Bends forward (flexion) and leans back (extension) with lower-back support.", "One direction or incorrect technique."),
      T("SPINE — ROM lateral bending", "Bends sideways right and left, sliding hands down the legs.", "One side or allows flexion/rotation."),
      T("SPINE — ROM rotation", "Rotates the upper body right and left while the pelvis stays stable.", "One direction or allows hip movement."),
      T("SPINE — Straight leg raise (SLR)", "Supine; raises each leg to ≥60° with knee extended, asking about pain.", "One side, bent knee, or fails to ask about symptoms."),
    ],
    addOns: [
      T("Thompson test (Achilles rupture)", "Squeezes the calf, patient prone with feet over the table edge, observing for passive plantarflexion.", "Incorrect positioning, inadequate squeeze, or no observation of foot movement."),
      T("Talar tilt test (ankle instability)", "Stabilizes the lower leg and inverts/everts the foot to assess ligament laxity.", "Incorrect hand placement, minimal movement, or one side only."),
      T("Phalen test (carpal tunnel)", "Holds wrists in full flexion for 60 s while asking about paresthesia.", "Too short, unclear instructions, or no symptom inquiry."),
      T("Tinel's sign (carpal tunnel)", "Taps over the median nerve at the wrist and asks about tingling in the median distribution.", "Incorrect location or no symptom inquiry."),
    ],
  },
  {
    id: "heent", name: "HEENT", color: "#68357C",
    blurb: "Careful assessment of the eyes, ears, nose, oral cavity, and related cranial nerves. Core maneuvers set visual, auditory, and oropharyngeal baselines; cluster maneuvers are added for infection, inflammation, obstruction, or neurologic involvement.",
    presentations: ["Sore throat", "Ear pain / discharge", "Hearing loss / tinnitus", "Nasal congestion / rhinorrhea", "Sinus pressure or pain", "Epistaxis", "Red eye / eye pain", "Blurred vision", "Hoarseness", "Oral lesions"],
    coreTasks: ["Observes general appearance", "Measures vital signs (BP, pulse, RR)", "Pupillary light reflex (CN II/III)", "Extraocular movements (CN III/IV/VI)", "Inspects oral cavity and oropharynx with light", "Palpates cervical lymph nodes", "Inspects external ears", "Gross hearing (CN VIII)"],
    clusterTasks: [
      T("Visual acuity (Snellen card or wall chart)", "Assesses both eyes one at a time AND occludes the untested eye; glasses kept on; held at 14 inches (or chart distance).", "One eye only, no occlusion, incorrect distance, or forgot glasses when applicable."),
      T("Assesses CN II (visual fields)", "Patient at eye level fixes gaze; student brings a finger from the periphery in all four quadrants of both eyes (or finger-counting).", "Fewer than four quadrants, no fixed gaze, or performed too quickly/close."),
      T("Uses ophthalmoscope correctly", "Assesses both eyes, right-to-right and left-to-left (unless panoptic); light must illuminate the pupil.", "One eye, incorrect eye-hand alignment, or light not through the pupil."),
      T("Uses otoscope correctly", "Examines both ears, pulls back the ear to straighten the canal, braces the instrument against the head, no pain.", "One ear, no ear traction, no bracing, or light not positioned into the canal."),
      T("Palpates sinuses for tenderness", "Fingertips gently palpate frontal (above brows) and maxillary (under cheekbones) sinuses bilaterally, asking about tenderness.", "One set or one side only, or forgets to ask about tenderness."),
      T("CN IX & X (gag/soft palate)", "Asks patient to open mouth and say 'ah' using a tongue depressor and light source.", "Misses a step (no illumination or inspection)."),
      T("Palpates thyroid (front or side)", "Palpates below the larynx with fingers AND asks the patient to swallow, without causing discomfort.", "Wrong area, didn't ask to swallow, or excessive pressure."),
    ],
    addOns: [
      T("Assesses nasal patency", "Occludes one nostril at a time, asks patient to sniff, compares airflow bilaterally.", "One nostril, unclear instructions, or no comparison."),
      T("Inspects nasal cavity with light", "Uses a light source to inspect the anterior nasal cavity bilaterally for septum and mucosa.", "One side, inadequate lighting, or doesn't visualize septum and mucosa."),
      T("Assesses tonsils", "Tongue depressor + light, mouth open wide, inspects both tonsils for size, symmetry, erythema, exudate.", "Brief, one side, poor lighting, or no tongue depressor when needed."),
      T("Performs Weber test", "Vibrating tuning fork at forehead midline; asks whether sound is equal or lateralizes.", "Incorrect placement, no lateralization confirmation, or no equal-perception check."),
      T("Performs Rinne test (AC vs BC)", "Tuning fork on mastoid until sound stops, then in front of the canal to compare air vs bone conduction.", "Only one portion, incorrect placement, unclear instructions, or no AC/BC comparison."),
      T("Assesses trismus (jaw opening)", "Asks patient to open the mouth fully; evaluates restriction, pain, symmetry, ease.", "Unclear instructions, brief inspection, or fails to note limitation/discomfort."),
      T("Cervical range of motion", "Flex, extend, rotate, and laterally bend the neck, observing symmetry and discomfort.", "Fewer than all planes, unclear instruction, or inadequate observation."),
      T("Inspects conjunctiva and sclera", "Retracts lower lids and uses a light to inspect conjunctiva/sclera bilaterally for color, injection, pallor.", "One eye, inadequate retraction, or poor lighting."),
      T("Assesses periorbital edema", "Inspects both lids for swelling, compares sides, palpates for firmness/pitting.", "One side, incorrect palpation, or no comparison."),
      T("Nystagmus (brief screen)", "Patient looks straight then in all cardinal directions while observing eye movements.", "Primary gaze only, no full assessment, or too brief."),
    ],
  },
  {
    id: "gu", name: "Genitourinary", color: "#0073A2",
    blurb: "Focused assessment of hydration status, flank discomfort, suprapubic tenderness, and related abdominal/pelvic findings. Core maneuvers evaluate systemic and abdominal contributors; cluster maneuvers are added for infection, obstruction, renal pathology, or lower urinary tract involvement.",
    presentations: ["Dysuria", "Urinary frequency / urgency", "Flank pain", "Hematuria", "Pelvic pain", "Scrotal / testicular pain or swelling", "Penile discharge or lesions", "Urinary incontinence", "Vaginal discharge or discomfort", "Lower abdominal pain (GU overlap)"],
    coreTasks: ["Observes general appearance", "Measures blood pressure", "Measures pulse", "Measures respiratory rate", "Inspects abdomen", "Auscultates abdomen before palpation", "Light abdominal palpation (all 4 quadrants)", "Deep abdominal palpation (all 4 quadrants)", "Assesses gait (if pain affects mobility)"],
    clusterTasks: [
      T("Assesses for CVA tenderness", "Locates the CVA bilaterally, places a flat hand over the angle, percusses with a closed fist, asks about pain each side.", "No flat hand, wrong location, one side only, or struck too forcefully/lightly."),
      T("Palpates inguinal lymph nodes", "Palpates the inguinal crease bilaterally with firm but gentle pressure for size/tenderness/enlargement.", "One side, superficial pressure, or unclear technique."),
      T("Suprapubic tenderness assessment", "Palpates the suprapubic region with gradual pressure, asking about discomfort or bladder fullness.", "Too brief, insufficient pressure, or no symptom assessment."),
      T("Performs rectal exam (when indicated)", "Explains, maintains privacy, inspects perianal area, palpates rectally for masses/tenderness/tone/prostate.", "Poor draping, incomplete inspection/palpation, or inadequate communication."),
      T("Assesses bladder distention", "Palpates from the umbilicus downward toward the pelvis with firm pressure to identify a distended bladder.", "Incorrect, brief, or insufficient pressure."),
      T("Evaluates urethral meatus", "Inspects the urethral meatus with proper tissue retraction for erythema, discharge, or lesions.", "Inadequate retraction, incomplete visualization, or too brief."),
      T("MALE — Scrotal exam", "Inspects and palpates each testicle, epididymis, and spermatic cord for tenderness/swelling/masses, comparing sides.", "One side, incomplete structures, or unclear technique."),
      T("MALE — Penis exam", "Retracts foreskin if present, inspects glans/shaft for lesions/swelling/discharge, examines the meatus.", "Inadequate visualization, no foreskin retraction, or incomplete meatal inspection."),
      T("MALE — Hernia exam", "Palpates the inguinal canal while the patient strains/coughs, comparing both sides for impulse/defect.", "One side, incorrect canal palpation, or unclear instruction."),
      T("MALE — Prostate exam (via rectal)", "Palpates the prostate for size, symmetry, nodules, tenderness as part of the rectal exam.", "Incorrect/incomplete palpation or fails to assess all prostate features."),
      T("FEMALE — Pelvic exam (when indicated)", "Appropriate draping, inspects external genitalia, speculum and bimanual exam as indicated, communicating throughout.", "Incomplete steps, inadequate draping, unclear instructions, or missing components."),
      T("FEMALE — Cervical motion tenderness", "Bimanual exam, moves the cervix gently side to side, asks about pain.", "Incorrect technique, omits pain query, or incomplete movement."),
      T("FEMALE — Adnexal tenderness/masses", "Palpates the adnexa bilaterally bimanually, noting tenderness or masses.", "One side, incorrect hand positioning, or inadequate assessment."),
      T("FEMALE — Evaluates vaginal discharge", "Visualizes vaginal walls and cervix with a speculum, assessing color, discharge, lesions, bleeding.", "Poor visualization, inadequate speculum placement, or incomplete inspection."),
    ],
    addOns: [],
  },
  {
    id: "endo", name: "Endocrine & Systemic", color: "#58595B",
    blurb: "Broad assessment of appearance, vital signs, hydration, and targeted organ findings. Core maneuvers form a general metabolic/systemic baseline; cluster tasks are added when thyroid, adrenal, or multisystem pathology is suspected. Many of these concerns require a multisystem examination.",
    presentations: ["Fatigue", "Weight loss", "Weight gain", "Heat or cold intolerance", "Polydipsia / polyuria", "Weakness", "Jaundice", "Memory problems / cognitive change", "Generalized edema", "Hair loss", "Skin changes"],
    coreTasks: ["Washes hands before exam", "Orientation to person, place, time", "Measures blood pressure", "Measures pulse rate", "Measures respiratory rate", "Inspects oral cavity and dentition", "CN VII (facial muscles)", "CN VIII (gross hearing)", "Palpates cervical lymph node chains", "Auscultates posterior chest (3 levels)", "Auscultates anterior chest (2 levels)", "Auscultates chest in 4 areas", "Inspects abdomen", "Auscultates abdomen before palpation", "Light abdominal palpation", "Deep abdominal palpation", "UE motor strength (≥2 groups/arm)", "LE motor strength (≥2 groups/leg)", "Assesses gait", "Washes hands after exam"],
    clusterTasks: [
      T("Palpates thyroid (front or side)", "Palpates below the larynx with fingers AND asks the patient to swallow, without causing discomfort.", "Wrong area, didn't ask to swallow, or excessive pressure."),
      T("UE motor strength (≥2 groups)", "Assesses ≥2 muscle groups in BOTH upper extremities against resistance.", "Fewer than two groups per side, passive movement, or weak resistance."),
      T("LE motor strength (≥2 groups)", "Assesses ≥2 muscle groups in BOTH lower extremities against resistance.", "Fewer than two groups per side, passive movement, or weak resistance."),
    ],
    addOns: [
      T("Inspects hair distribution", "Inspects scalp and visible body hair for thinning, loss, texture change, or pattern abnormalities.", "Brief, one area only, or inadequate lighting."),
      T("Inspects skin (hyperpigmentation, vitiligo, dryness)", "Examines skin of face, trunk, extremities for pigmentation changes, moisture, lesions.", "Incomplete inspection, poor lighting, or limited area."),
      T("Assesses for pedal edema", "Palpates both anterior shins over bone with firm pressure for pitting edema.", "One side, non-bony area, or insufficient pressure."),
      T("Assesses for hepatosplenomegaly", "Palpates liver edge and spleen with proper technique, coordinating with inspiration.", "Incorrect hand position, insufficient depth, or one organ only."),
      T("Performs orthostatic vitals", "Measures BP and pulse supine (3 min) and standing (1 and 3 min), comparing changes.", "Once only, improper timing, or omits pulse."),
      T("Assesses for tremor (rest vs action)", "Observes hands at rest and during movement for tremor frequency, amplitude, symmetry.", "Brief observation, only rest or movement, or poor visualization."),
      T("Brief cognitive screen", "Assesses orientation, attention (serial 7s), recall, and language.", "Incomplete domains, unclear instructions, or inadequate observation."),
    ],
  },
];

// Illness scripts (Appendix A) — 73 presenting complaints, each tagged to a cluster/system.
export const SCRIPTS = [
  { name: "Abdominal, Flank, Back Pain", system: "gi" },
  { name: "Abnormal Uterine Bleeding", system: "gu" },
  { name: "Alopecia (Hair Loss)", system: "endo" },
  { name: "Amenorrhea (Missed or Absent Periods)", system: "gu" },
  { name: "Anal and Perianal Lesions", system: "gi" },
  { name: "Ankle Pain or Swelling", system: "msk" },
  { name: "Anxiety and Excessive Worrying", system: "neuro" },
  { name: "Blurred Vision", system: "heent" },
  { name: "Breast Discomfort or Pain", system: "gu" },
  { name: "Breast Mass / Lump", system: "gu" },
  { name: "Chest Pain", system: "cardiac" },
  { name: "Constipation", system: "gi" },
  { name: "Cough", system: "pulmonary" },
  { name: "Defecation Pain", system: "gi" },
  { name: "Depressed Mood", system: "neuro" },
  { name: "Diarrhea", system: "gi" },
  { name: "Dizziness / Light-Headedness", system: "neuro" },
  { name: "Dysmenorrhea (Painful Periods)", system: "gu" },
  { name: "Earache / Discharge", system: "heent" },
  { name: "Edema (Swelling)", system: "cardiac" },
  { name: "Elbow Pain", system: "msk" },
  { name: "Epigastric Pain", system: "gi" },
  { name: "Epistaxis (Nosebleed)", system: "heent" },
  { name: "Erectile Dysfunction", system: "gu" },
  { name: "Fatigue", system: "endo" },
  { name: "Foot Pain", system: "msk" },
  { name: "Gum Bleeding or Swelling", system: "heent" },
  { name: "Headache", system: "neuro" },
  { name: "Hearing Loss / Tinnitus", system: "heent" },
  { name: "Hematemesis (Vomiting Blood)", system: "gi" },
  { name: "Hematochezia (Blood in Stools)", system: "gi" },
  { name: "Hemoptysis (Coughing Up Blood)", system: "pulmonary" },
  { name: "Hip Pain", system: "msk" },
  { name: "Hoarseness", system: "heent" },
  { name: "Hypogastric (Suprapubic) Pain", system: "gu" },
  { name: "Jaundice", system: "endo" },
  { name: "Knee Pain", system: "msk" },
  { name: "Left Lower Quadrant (LLQ) Pain", system: "gi" },
  { name: "Left Upper Quadrant (LUQ) Pain", system: "gi" },
  { name: "Lesion", system: "endo" },
  { name: "Low Back Pain", system: "msk" },
  { name: "Memory Problems", system: "neuro" },
  { name: "Nasal Congestion / Rhinorrhea", system: "heent" },
  { name: "Nausea and Vomiting", system: "gi" },
  { name: "Neck Mass or Lump", system: "heent" },
  { name: "Neck Pain or Stiffness", system: "msk" },
  { name: "Nipple Discharge", system: "gu" },
  { name: "Pelvic Pain", system: "gu" },
  { name: "Pain/Swelling with Intermittent Claudication, Lower Extremities", system: "cardiac" },
  { name: "Pain/Swelling, Lower Extremities", system: "cardiac" },
  { name: "Palpitations", system: "cardiac" },
  { name: "Penile Lesion or Discharge", system: "gu" },
  { name: "Pruritus (Itching)", system: "endo" },
  { name: "Rash", system: "endo" },
  { name: "Red Eye / Eye Pain", system: "heent" },
  { name: "Right Lower Quadrant (RLQ) Pain", system: "gi" },
  { name: "Right Upper Quadrant (RUQ) Pain", system: "gi" },
  { name: "Scrotal or Testicular Pain, Swelling, or Lesions", system: "gu" },
  { name: "Seizures", system: "neuro" },
  { name: "Shortness of Breath", system: "pulmonary" },
  { name: "Shoulder Pain", system: "msk" },
  { name: "Sore Throat", system: "heent" },
  { name: "Syncope and Near-Syncope", system: "cardiac" },
  { name: "Thyroid Mass, Nodule, or Goiter", system: "endo" },
  { name: "Urinary Incontinence", system: "gu" },
  { name: "Urinary Tract (Lower) Symptoms", system: "gu" },
  { name: "Vertigo", system: "neuro" },
  { name: "Vulvovaginal Symptoms", system: "gu" },
  { name: "Weakness (Paresis)", system: "neuro" },
  { name: "Weight Gain", system: "endo" },
  { name: "Weight Loss", system: "endo" },
  { name: "Wrist and Hand Pain or Stiffness", system: "msk" },
];

export const DEVICES = [
  { name: "Amputated Limb", category: "Orthopedic", device: "Removal of a limb or part of a limb, usually due to trauma, disease, or congenital conditions.", indication: "Trauma, peripheral vascular disease, tumors, or severe infections not managed conservatively.", location: "Varies with amputation site (e.g., above-knee, below-knee, arm).", mods: ["Ask the patient to remove the prosthetic limb if present.", "Inspect the stump for skin irritation, breakdown, or ulcers.", "Palpate the stump gently for warmth, fluctuance, tenderness, or bony spurs.", "Evaluate the limb for hygiene and vascular status.", "Ask about phantom limb sensations or pain.", "Inquire about comfort, function, and any change in prosthesis fit."] },
  { name: "Arteriovenous (AV) Fistula or Graft", imgs: ["assets/devices/av-fistula.png"], category: "Vascular", device: "Surgical artery–vein connection (or graft) for permanent vascular access, typically in the arm.", indication: "Long-term vascular access for hemodialysis in chronic kidney disease / ESRD.", location: "Most commonly forearm or upper arm; can be created in the leg.", mods: ["Inspect for infection, inflammation, or aneurysmal change.", "Palpate with the palm for the characteristic 'thrill' — absence indicates a problem.", "Auscultate for a bruit (soft machinery-like whoosh) — absence indicates a problem.", "Examine hand color, pulses, capillary refill for distal ischemia.", "Avoid using the fistula limb for BP measurement or venipuncture."] },
  { name: "Artificial Eye (Ocular Prosthesis)", imgs: ["assets/devices/artificial-eye.png"], category: "Sensory", device: "Acrylic or glass prosthetic eye replacing an absent natural eye.", indication: "Loss of an eye from injury or disease, or congenital anophthalmia.", location: "Within the orbit, behind the eyelids.", mods: ["Inspect for positioning, alignment with the other eye, and cosmetic appearance.", "Check eyelids and socket conjunctiva for irritation, infection, inflammation.", "Assess prosthetic movement relative to the natural eye on gaze.", "Ask about discomfort, discharge, or changes in fit/appearance."] },
  { name: "Implantable Cardioverter-Defibrillator (ICD)", imgs: ["assets/devices/icd.png"], category: "Cardiac", device: "Implanted device that detects and corrects life-threatening VT/VF by delivering a shock.", indication: "Prevention of sudden cardiac death in high-risk patients or those with prior VT/VF.", location: "Anterior chest wall, infraclavicular, with leads into the myocardium.", mods: ["Inspect for surgical scars, device protrusion, erythema, edema, skin change.", "Palpate gently — do not press hard over the device.", "On auscultation, soft electrical sounds may relate to device operation.", "Document device type, implantation date, and most recent battery change.", "Prior interrogation reports give insight on performance and arrhythmic episodes."] },
  { name: "Breast Augmentation or Reconstruction", imgs: ["assets/devices/breast-augmentation.png"], category: "Surgical", device: "Insertion of breast implants (silicone/saline) under tissue or chest muscle.", indication: "Augmentation, post-mastectomy reconstruction, or asymmetry correction.", location: "Behind breast tissue above the pectoral muscle, or submuscular.", mods: ["Inspect for asymmetry, skin changes, rippling, or implant complications.", "Palpate to distinguish implant from natural tissue, feeling for edges.", "Assess tissue above/around the implant for new masses.", "If submuscular, palpate separately with the chest muscles flexed.", "Check for rupture signs (asymmetry, shape change).", "Use pads of first three fingers; examine axillary nodes for silicone migration."] },
  { name: "Breast Reduction Surgery", imgs: ["assets/devices/breast-reduction.png"], category: "Surgical", device: "Removal of excess breast tissue, fat, and skin.", indication: "Physical discomfort from large breasts or aesthetic reasons.", location: "Incisions around the areola, vertically to the crease, or along the crease.", mods: ["Inspect for surgical scars, skin changes, or nipple position change.", "Palpate gently in a circular motion; check for lumpiness or thickening near scars.", "Assess nipple sensation, vascular supply, and any discharge.", "Examine the infra-mammary fold and axilla for masses or lymphadenopathy."] },
  { name: "Central Venous Access Port", imgs: ["assets/devices/central-venous-port.png"], category: "Vascular", device: "Implanted venous access device with an externally accessible reservoir.", indication: "Long-term medications, chemotherapy, parenteral nutrition, or frequent blood draws.", location: "Subcutaneous, upper chest below the clavicle; catheter tip in the SVC / right atrium.", mods: ["Inspect overlying skin for infection or inflammation.", "Palpate gently around the port for flatness and tenderness.", "Auscultate if vascular complication is suspected.", "Do not access the port unless specially trained; use aseptic technique."] },
  { name: "Cochlear Implant", imgs: ["assets/devices/cochlear-implant.png"], category: "Sensory", device: "Implanted device that stimulates the auditory nerve directly, bypassing damaged ear structures.", indication: "Moderate-to-profound sensorineural hearing loss with limited hearing-aid benefit.", location: "External component behind the ear; internal component implanted into the cochlea.", mods: ["Examine the external component gently — avoid tugging or pulling.", "Be cautious near the implanted internal device to avoid pressure.", "Inspect for skin irritation or breakdown around the external site.", "Avoid deep otoscopy if implant position is uncertain."] },
  { name: "Dental Implants", imgs: ["assets/devices/dental-implants.png"], category: "Oral", device: "Fixed prosthetic devices anchored into the jawbone to replace missing teeth.", indication: "One or more missing teeth seeking a permanent solution.", location: "Implanted into the maxillary or mandibular jawbone.", mods: ["No removal necessary (fixed prosthetics).", "Inspect surrounding gum for inflammation, infection, recession (peri-implantitis).", "Check stability/condition of the crown or bridge.", "Ask about discomfort or changes in bite/fit.", "Recommend regular oral hygiene around the implant."] },
  { name: "Dentures", imgs: ["assets/devices/dentures.png"], category: "Oral", device: "Removable prosthetic devices replacing missing teeth.", indication: "Some (partial) or all (complete) teeth missing.", location: "Oral cavity, replacing maxillary and/or mandibular teeth.", mods: ["Ask the patient to remove dentures for a thorough oral exam.", "Inspect mucosa beneath for irritation, denture stomatitis, ulceration, tumors.", "Examine the fit and condition of the dentures.", "Ask about discomfort or changes in fit/bite.", "Recommend daily cleaning and overnight soaking."] },
  { name: "Hearing Aid", imgs: ["assets/devices/hearing-aid-1.png","assets/devices/hearing-aid-2.png","assets/devices/hearing-aid-3.png"], category: "Sensory", device: "Electronic device that amplifies sound for hearing loss.", indication: "Mild-to-severe hearing loss with an intact auditory pathway.", location: "Behind-the-ear, in-the-ear, in-the-canal, or completely-in-canal designs.", mods: ["Ask the patient to remove the device before examination.", "Inspect the ear canal for irritation from the device.", "Check for cerumen or debris that can clog the device.", "Be gentle with otoscopy to avoid dislodging in-ear devices."] },
  { name: "Hemodialysis / Dialysis Catheter", imgs: ["assets/devices/hemodialysis-catheter.png"], category: "Vascular", device: "Catheter for hemodialysis — removing excess fluid and waste when kidneys fail.", indication: "Temporary or permanent hemodialysis access in CKD / ESRD.", location: "Internal jugular, subclavian, or femoral vein; tip in the right atrium / SVC.", mods: ["Inspect the site for infection or inflammation, including purulent discharge.", "Palpate around the site for tenderness or induration.", "Auscultate over the insertion site if vascular complication suspected.", "Use aseptic technique; avoid using the area for other venous access."] },
  { name: "Implantable Continuous Glucose Monitor", imgs: ["assets/devices/glucose-monitor.png"], category: "Endocrine", device: "Subcutaneous sensor measuring interstitial glucose and transmitting readings.", indication: "Continuous glucose monitoring for better diabetes management.", location: "Subcutaneous tissue of the upper arm or abdomen.", mods: ["Inspect the area for discoloration, scars, or trauma.", "Examine the site for erythema, swelling, or discharge.", "Palpate gently around (not over) the device for nodules or induration.", "Ask about pain/discomfort on palpation.", "Be aware of device boundaries to avoid dislodgement."] },
  { name: "Indwelling Urinary Catheter (Foley)", imgs: ["assets/devices/foley-catheter.png"], category: "Urologic", device: "Flexible tube through the urethra into the bladder, secured with a saline balloon.", indication: "Urinary retention, perioperative use, or output monitoring.", location: "Urethra with tip in the bladder; tubing secured to the thigh.", mods: ["Ask permission and explain each step.", "Inspect the meatus for irritation, leakage, skin breakdown; avoid foreskin retraction.", "Inspect and palpate genitalia, avoiding tension on the catheter.", "Avoid pressure over the bladder balloon.", "Ask about discomfort, urine appearance, output, or leakage."] },
  { name: "Insulin Pump", imgs: ["assets/devices/insulin-pump.png"], category: "Endocrine", device: "Delivers insulin continuously or in boluses via a subcutaneous cannula.", indication: "Intensive insulin therapy as an alternative to multiple daily injections.", location: "Worn on belt/pocket; infusion set on the abdomen or thigh subcutaneous tissue.", mods: ["Identify the infusion-set location on the skin.", "Inspect for irritation, redness, swelling, or skin breakdown.", "Palpate gently around (not over) the site for leakage or lipohypertrophy.", "Check the adhesive for allergic reaction or skin breakdown.", "Ask about cleaning and site-rotation routine.", "If moved for exam, do so carefully to avoid dislodging the set."] },
  { name: "Intrathecal Catheter or Pump", imgs: ["assets/devices/intrathecal-pump.png"], category: "Neurologic", device: "Catheter in the intrathecal space for drug delivery into the CSF.", indication: "Chemotherapy, spasticity, or intractable pain medications.", location: "Pump in the abdomen/low back or external; catheter usually in the lumbar region.", mods: ["Avoid pressure at the catheter entry site to prevent dislodgement.", "Assess for infection, inflammation, or CSF leakage at the site.", "Watch the mental-status/neuro exam for toxicity, overdose, or withdrawal.", "Palpate any implanted pump gently; inspect for malfunction/infection.", "Assess pain level, muscle tone, and medication-specific indicators."] },
  { name: "Intrauterine Device (IUD)", imgs: ["assets/devices/iud.png"], category: "Reproductive", device: "Small T-shaped device inserted into the uterus to prevent pregnancy.", indication: "Long-term reversible contraception.", location: "Uterine cavity, with strings through the cervix into the vagina.", mods: ["Explain steps and reason for the exam.", "Inspect the cervix for IUD strings; avoid tugging or pulling them.", "Palpate gently on the bimanual exam to avoid displacing the IUD.", "If strings are not located, consider ultrasound to confirm position.", "Advise the patient to check string presence regularly."] },
  { name: "Joint Prosthesis", imgs: ["assets/devices/joint-prosthesis-hip.png","assets/devices/joint-prosthesis-knee.png"], category: "Orthopedic", device: "Damaged joint replaced with a metal/plastic/ceramic implant.", indication: "End-stage joint disease (OA, RA, trauma) unresponsive to conservative care.", location: "Most commonly hip, knee, shoulder; less often elbow, wrist, ankle.", mods: ["Inspect for scars and signs of inflammation/infection or effusion.", "Palpate for warmth, tenderness, or abnormal fluid collections.", "Ask about pain or limitations before manipulating the joint.", "Examine ROM gently — expect limitations vs a natural joint.", "Assess neurovascular status distal to the prosthesis.", "Ask about function, clicking/grinding, and changes in ROM."] },
  { name: "Mastectomy", category: "Surgical", device: "Surgical removal of one or both breasts, partial or complete.", indication: "Breast cancer treatment or high-risk preventive measure.", location: "Entire breast tissue removed, often with nipple and areola.", mods: ["Inspect for surgical scars, skin changes, contour irregularities.", "Palpate the chest wall for new masses, irregularities, or skin tethering.", "Check ipsilateral arm ROM and examine for lymphedema.", "For reconstructed breasts, follow the breast-augmentation guidelines.", "Examine axillary and supraclavicular regions for lymphadenopathy."] },
  { name: "Mechanical Ventilator", category: "Respiratory", device: "Machine providing artificial ventilation by moving air into and out of the lungs.", indication: "Respiratory failure, general anesthesia, or severe pneumonia/asthma.", location: "Bedside in ICU/wards; tubing connects to an ET or tracheostomy tube.", mods: ["Inspect tubing connections/positioning to avoid pull or disconnection.", "Auscultate lung fields bilaterally for even ventilation and adventitious sounds.", "Monitor settings (tidal volume, pressures, RR, SpO₂) — do not adjust alone.", "Ask about discomfort, respiratory change, or ventilator alarms."] },
  { name: "Ostomy (Ileostomy / Colostomy)", category: "GI", device: "Pouching system collecting waste from a surgically created stoma.", indication: "Bypass of an injured/diseased colon or post-resection stool diversion.", location: "Often the lower abdomen, depending on ostomy type.", mods: ["Inspect peristomal skin for irritation or infection.", "Check stoma color — should be moist and pink/red.", "Palpate gently around the stoma without pressing directly on it.", "Assess ostomy output consistency, color, and quantity.", "Ask consent before inspecting/palpating; ask about discomfort or output change."] },
  { name: "Pacemaker", category: "Cardiac", device: "Implanted device generating electrical impulses to maintain a normal heart rate.", indication: "Sinus node dysfunction, symptomatic bradycardia, high-grade/symptomatic AV block.", location: "Anterior chest wall, infraclavicular; transvenous leads into the myocardium.", mods: ["Inspect for scars, device protrusion, erythema, edema, or skin change.", "Palpate gently for warmth, tenderness, or local complications.", "On auscultation, a soft ticking sound may relate to device operation.", "Document model, implantation date, most recent battery change.", "Obtain a 12-lead ECG and prior interrogation reports if indicated."] },
  { name: "Penile Implant (Prosthesis)", category: "Urologic", device: "Inflatable cylinders or malleable rods implanted to treat erectile dysfunction.", indication: "ED refractory to other treatments; penile injury or deformity.", location: "Corpora cavernosa; inflatable types add an abdominal reservoir and scrotal pump.", mods: ["Ask permission and explain each step.", "Ask about implant type (inflatable vs malleable) and special considerations.", "Inquire about function and issues with sexual activity or urination.", "Inspect for infection, inflammation, or skin breakdown.", "Palpate gently — avoid unintentionally activating an inflatable device.", "Check for malfunction signs (asymmetry, firm nodules)."] },
  { name: "PEG / PEJ Feeding Tube", category: "GI", device: "Tube through the abdominal wall into the stomach (PEG) or jejunum (PEJ) for enteral nutrition.", indication: "Nutritional support with inadequate oral intake but a functioning GI tract.", location: "Typically the left upper quadrant of the abdomen.", mods: ["Inspect for infection, skin irritation, or leakage.", "Palpate gently around the tube site for tenderness, swelling, discharge.", "Avoid direct pressure over the tube site.", "Ask about discomfort, pain, and tube function.", "Note dislodgement or evidence of blockage."] },
  { name: "PICC / Midline Catheter", category: "Vascular", device: "Catheter inserted in a peripheral vein for prolonged vascular access.", indication: "Short- to intermediate-term medications, especially prolonged IV antibiotics.", location: "Cubital/brachial vein; PICC tip in the SVC, midline tip near the shoulder.", mods: ["Inspect the site for infection or inflammation, including purulent discharge.", "Palpate around the site for tenderness or induration.", "Use aseptic technique when accessing the catheter.", "Avoid using an area proximal to the catheter for other venous access."] },
  { name: "Peritoneal Dialysis Catheter", category: "Vascular", device: "Catheter for filling/draining dialysis solution from the peritoneal cavity.", indication: "Treatment of ESRD/kidney failure — removing waste and excess fluid.", location: "Through the lower abdominal wall into the peritoneal cavity.", mods: ["Inspect the site for skin irritation or infection.", "Palpate gently around the catheter for warmth or tenderness.", "Don't tug or pull on the catheter.", "Examine for hernias, especially near the catheter site.", "Check for abdominal distension; evaluate for peritonitis (tenderness, infection)."] },
  { name: "Phalloplasty", category: "Reproductive", device: "Neophallus constructed using tissue grafts (forearm, thigh, or back).", indication: "Gender-confirmation surgery, congenital anomaly, or post-trauma reconstruction.", location: "Anatomic location of the penis, using grafted tissue.", mods: ["Approach with sensitivity; ask permission and explain each step.", "Ask about sexual function, ability to pass urine, and other concerns.", "Inspect the neophallus — scars, grafts, appearance, urethral patency.", "Inspect for infection, inflammation, or discharge from the urethral opening.", "Palpate gently, mindful of the patient's sensitivity."] },
  { name: "Prosthetic Limb", category: "Orthopedic", device: "Artificial device replacing a missing or impaired limb.", indication: "Improve function/mobility, or cosmetic reasons, after amputation.", location: "Attached to the residual limb (stump); varies by limb replaced.", mods: ["Ask if the patient can remove the prosthesis for the exam.", "Inspect the residual-limb skin for pressure sores or irritation.", "Palpate the stump for tender areas or bony prominences.", "Check the fit and alignment of the prosthesis.", "Ask about function, noises (clicking/grinding), stability, and fit changes."] },
  { name: "Suprapubic Catheter", category: "Urologic", device: "Tube inserted directly into the bladder through the abdominal wall for drainage.", indication: "Direct urinary drainage; alternative to urethral catheterization.", location: "Through the abdominal wall with the tip in the bladder.", mods: ["Ask permission and explain each step.", "Inspect the suprapubic area and genitalia for redness, discharge, swelling, leakage.", "Palpate without direct pressure on the insertion site; avoid tubing tension.", "Ask about discomfort, urine output/appearance, obstruction, or leakage."] },
  { name: "Thoracostomy Tube (Chest Tube)", category: "Respiratory", device: "Tube through the chest wall into the pleural space to remove air, fluid, blood, or pus.", indication: "Pneumothorax, hemothorax, empyema, or large pleural effusions.", location: "Fifth intercostal space, slightly anterior to the midaxillary line.", mods: ["Remove kinks/obstructions; ensure tubing is not under tension.", "Inspect the insertion site for redness, swelling, infection.", "Palpate for subcutaneous emphysema.", "Auscultate all lung fields for breath/adventitious sounds.", "Evaluate drainage amount/type; assess bubbling for air leak.", "Do not manipulate without an experienced provider."] },
  { name: "Tracheostomy Tube", category: "Respiratory", device: "Tube into a surgically created opening in the anterior neck and trachea for an airway.", indication: "Long-term ventilation, airway support, obstruction bypass, or secretion clearance.", location: "Anterior midline neck, entering directly into the trachea.", mods: ["Inspect the skin around the site for redness, swelling, or infection.", "Assess the stoma for patency and discharge.", "Auscultate for breath sounds around the tracheostomy.", "Palpate gently for subcutaneous emphysema.", "Ask about discomfort or breathing difficulty.", "Do not remove the tube without an experienced provider."] },
  { name: "Vaginoplasty", category: "Reproductive", device: "Surgical construction or reconstruction of the vagina.", indication: "Gender-confirmation surgery, congenital anomaly, or post-trauma reconstruction.", location: "Anatomic location of the vagina.", mods: ["Approach with sensitivity; ask permission and explain each step.", "Take a thorough history of surgery type and complications.", "Proceed gently with adequate lubrication (neovagina elasticity differs).", "Inspect external genitalia for scars, erythema, edema, or trauma.", "On internal exam, know the neovagina depth/angle; note strictures, bleeding, discharge.", "Palpate for masses/tenderness; be aware of possible retained prostate tissue."] },
  { name: "Ventriculoperitoneal Shunt", category: "Neurologic", device: "Implanted device draining excess CSF from the brain's ventricles to the peritoneum.", indication: "Hydrocephalus or increased intracranial pressure.", location: "Ventricle → subcutaneous neck/chest → peritoneal cavity; valve often behind the ear.", mods: ["Palpate the shunt course gently to prevent dislodgement.", "Assess the course and valve (behind the ear) for infection signs.", "Watch for malfunction → raised ICP: headache, vomiting, irritability, altered consciousness, focal deficits, papilledema.", "Compare neurologic findings with baseline when available."] },
];

export const ABBREVIATIONS = [
  ["AC", "Air conduction"], ["AC", "Acromioclavicular joint"], ["ACEI", "Angiotensin-converting enzyme inhibitor"], ["ACL", "Anterior cruciate ligament"], ["ACS", "Acute coronary syndrome"], ["ALS", "Amyotrophic lateral sclerosis"], ["AMS", "Altered mental status"], ["AVM", "Arteriovenous malformation"], ["BC", "Bone conduction"], ["BNP", "B-type natriuretic peptide"], ["BP", "Blood pressure"], ["BV", "Bacterial vaginosis"], ["CABG", "Coronary artery bypass grafting"], ["CAD", "Coronary artery disease"], ["CAM", "Complementary and alternative medicine"], ["CBC", "Complete blood count"], ["CBE", "Clinical breast examination"], ["CBT", "Cognitive behavioral therapy"], ["CDC", "Centers for Disease Control and Prevention"], ["CHF", "Congestive heart failure"], ["CK-MB", "Creatine kinase-MB"], ["CNS", "Central nervous system"], ["COPD", "Chronic obstructive pulmonary disease"], ["CRP", "C-reactive protein"], ["CSF", "Cerebrospinal fluid"], ["CT", "Computed tomography"], ["CVAT", "Costovertebral angle tenderness"], ["CVI", "Chronic venous insufficiency"], ["CVST", "Cerebral venous sinus thrombosis"], ["CXR", "Chest x-ray"], ["DIC", "Disseminated intravascular coagulation"], ["DMARD", "Disease-modifying antirheumatic drug"], ["DKA", "Diabetic ketoacidosis"], ["DLCO", "Diffusing capacity of the lungs for carbon monoxide"], ["DVT", "Deep vein thrombosis"], ["ECG", "Electrocardiogram"], ["ECT", "Electroconvulsive therapy"], ["EEG", "Electroencephalogram"], ["EGD", "Esophagogastroduodenoscopy"], ["EMG", "Electromyography"], ["ERCP", "Endoscopic retrograde cholangiopancreatography"], ["ERP", "Exposure and response prevention"], ["ESR", "Erythrocyte sedimentation rate"], ["ETT", "Exercise treadmill test"], ["FAIR", "Flexion, adduction, internal rotation"], ["FEV1", "Forced expiratory volume in one second"], ["FHR", "Fetal heart rate"], ["FM", "Fetal movement"], ["FNA", "Fine needle aspiration"], ["FSH", "Follicle-stimulating hormone"], ["FVC", "Forced vital capacity"], ["GA", "Gestational age"], ["GAD", "Generalized anxiety disorder"], ["GCA", "Giant cell arteritis"], ["GERD", "Gastroesophageal reflux disease"], ["GI", "Gastrointestinal"], ["GnRH", "Gonadotropin-releasing hormone"], ["HA", "Headache"], ["H&P", "History and physical"], ["HbA1c", "Hemoglobin A1c"], ["hCG", "Human chorionic gonadotropin"], ["HIV", "Human immunodeficiency virus"], ["HL", "Hearing loss"], ["HOCM", "Hypertrophic obstructive cardiomyopathy"], ["HSV", "Herpes simplex virus"], ["IBD", "Inflammatory bowel disease"], ["IBS", "Irritable bowel syndrome"], ["ICD", "Implantable cardioverter-defibrillator"], ["ICP", "Intracranial pressure"], ["IOP", "Intraocular pressure"], ["IUP", "Intrauterine pregnancy"], ["IV", "Intravenous"], ["IVC", "Inferior vena cava"], ["JVP", "Jugular venous pressure"], ["LE", "Lower extremity"], ["LH", "Luteinizing hormone"], ["LLSB", "Lower left sternal border"], ["LOF", "Loss of fluid"], ["LP", "Lumbar puncture"], ["LRTI", "Lower respiratory tract infection"], ["LUQ", "Left upper quadrant"], ["MCA", "Middle cerebral artery"], ["MCL", "Medial collateral ligament"], ["MDD", "Major depressive disorder"], ["MEP", "Maximum expiratory pressure"], ["MI", "Myocardial infarction"], ["MIP", "Maximum inspiratory pressure"], ["MNCD", "Mild neurocognitive disorder"], ["MR", "Mitral regurgitation"], ["MRI", "Magnetic resonance imaging"], ["MRCP", "Magnetic resonance cholangiopancreatography"], ["MS", "Multiple sclerosis"], ["NAAT", "Nucleic acid amplification test"], ["NAFLD", "Non-alcoholic fatty liver disease"], ["NGU", "Nongonococcal urethritis"], ["NPO", "Nothing by mouth"], ["N/V", "Nausea and vomiting"], ["NSAID", "Nonsteroidal anti-inflammatory drug"], ["OCD", "Obsessive-compulsive disorder"], ["OCT", "Optical coherence tomography"], ["OTC", "Over the counter"], ["PAC", "Premature atrial contraction"], ["PAD", "Peripheral artery disease"], ["PCOS", "Polycystic ovary syndrome"], ["PCI", "Percutaneous coronary intervention"], ["PDE5", "Phosphodiesterase type 5"], ["PET", "Positron emission tomography"], ["PFTs", "Pulmonary function tests"], ["PH", "Pulmonary hypertension"], ["PID", "Pelvic inflammatory disease"], ["PMN", "Polymorphonuclear neutrophil"], ["PNA", "Pneumonia"], ["PPI", "Proton pump inhibitor"], ["PSA", "Prostate-specific antigen"], ["PSH", "Past surgical history"], ["PTSD", "Posttraumatic stress disorder"], ["PUD", "Peptic ulcer disease"], ["PVC", "Premature ventricular contraction"], ["PVR", "Pulmonary vascular resistance"], ["RAI", "Radioactive iodine"], ["RBC", "Red blood cell"], ["RICE", "Rest, ice, compression, elevation"], ["R/O", "Rule out"], ["RUQ", "Right upper quadrant"], ["RV", "Residual volume"], ["SBO", "Small bowel obstruction"], ["SLE", "Systemic lupus erythematosus"], ["SLR", "Straight-leg raise"], ["SNRI", "Serotonin-norepinephrine reuptake inhibitor"], ["SOB", "Shortness of breath"], ["SpO₂", "Oxygen saturation"], ["SSRI", "Selective serotonin reuptake inhibitor"], ["STEMI", "ST-elevation myocardial infarction"], ["SVE", "Sterile vaginal exam"], ["T3", "Triiodothyronine"], ["T4", "Thyroxine"], ["TLC", "Total lung capacity"], ["TMJ", "Temporomandibular joint"], ["TSH", "Thyroid-stimulating hormone"], ["TVUS", "Transvaginal ultrasound"], ["UA", "Urinalysis"], ["UACS", "Upper airway cough syndrome"], ["UMN", "Upper motor neuron"], ["URI", "Upper respiratory infection"], ["URTI", "Upper respiratory tract infection"], ["UTI", "Urinary tract infection"], ["UV", "Ultraviolet"], ["VB", "Vaginal bleeding"], ["VEGF", "Vascular endothelial growth factor"], ["VSD", "Ventricular septal defect"], ["WBC", "White blood cell"],
].map(([abbr, meaning]) => ({ abbr, meaning }));

// Standard reference lab values — supplementary content (not from the source documents).
// Educational reference ranges; values vary by lab. Flagged as supplementary in the UI.
export const LABS = [
  { panel: "Complete Blood Count (CBC)", tests: [
    { name: "WBC", range: "4.5 – 11.0", units: "×10⁹/L" },
    { name: "Hemoglobin (M)", range: "13.5 – 17.5", units: "g/dL" },
    { name: "Hemoglobin (F)", range: "12.0 – 15.5", units: "g/dL" },
    { name: "Hematocrit (M)", range: "41 – 50", units: "%" },
    { name: "Hematocrit (F)", range: "36 – 44", units: "%" },
    { name: "Platelets", range: "150 – 400", units: "×10⁹/L" },
    { name: "MCV", range: "80 – 100", units: "fL" },
  ]},
  { panel: "Basic Metabolic Panel (BMP)", tests: [
    { name: "Sodium", range: "135 – 145", units: "mmol/L", critical: "<120 or >160" },
    { name: "Potassium", range: "3.5 – 5.0", units: "mmol/L", critical: "<2.5 or >6.5" },
    { name: "Chloride", range: "98 – 107", units: "mmol/L" },
    { name: "Bicarbonate", range: "22 – 29", units: "mmol/L" },
    { name: "BUN", range: "7 – 20", units: "mg/dL" },
    { name: "Creatinine", range: "0.6 – 1.3", units: "mg/dL" },
    { name: "Glucose (fasting)", range: "70 – 99", units: "mg/dL", critical: "<40 or >500" },
    { name: "Calcium", range: "8.5 – 10.5", units: "mg/dL" },
  ]},
  { panel: "Liver Function Tests (LFTs)", tests: [
    { name: "AST", range: "10 – 40", units: "U/L" },
    { name: "ALT", range: "7 – 56", units: "U/L" },
    { name: "Alkaline phosphatase", range: "44 – 147", units: "U/L" },
    { name: "Total bilirubin", range: "0.1 – 1.2", units: "mg/dL" },
    { name: "Albumin", range: "3.5 – 5.0", units: "g/dL" },
    { name: "Total protein", range: "6.0 – 8.3", units: "g/dL" },
  ]},
  { panel: "Cardiac & Inflammatory Markers", tests: [
    { name: "Troponin I", range: "<0.04", units: "ng/mL", critical: "Elevated → ACS" },
    { name: "BNP", range: "<100", units: "pg/mL", critical: ">400 → heart failure" },
    { name: "CRP", range: "<3.0", units: "mg/L" },
    { name: "ESR (M)", range: "0 – 15", units: "mm/hr" },
    { name: "ESR (F)", range: "0 – 20", units: "mm/hr" },
    { name: "D-dimer", range: "<0.50", units: "µg/mL FEU" },
  ]},
  { panel: "Thyroid & Endocrine", tests: [
    { name: "TSH", range: "0.4 – 4.0", units: "mIU/L" },
    { name: "Free T4", range: "0.8 – 1.8", units: "ng/dL" },
    { name: "HbA1c", range: "<5.7", units: "%", critical: "≥6.5 → diabetes" },
    { name: "Free T3", range: "2.3 – 4.2", units: "pg/mL" },
  ]},
  { panel: "Coagulation", tests: [
    { name: "PT", range: "11 – 13.5", units: "sec" },
    { name: "INR (no anticoag)", range: "0.8 – 1.1", units: "" },
    { name: "aPTT", range: "25 – 35", units: "sec" },
  ]},
];

// Standard clinical pathways — supplementary educational content (not from the source documents).
// Widely-accepted teaching algorithms; always follow local protocols and clinical judgment.
export const ALGORITHMS = [
  { id: "chestpain", name: "Acute Chest Pain Triage", system: "cardiac",
    summary: "Initial approach to undifferentiated chest pain — rule out the immediately life-threatening causes first.",
    steps: [
      { step: "Immediate", detail: "Obtain a 12-lead ECG within 10 minutes; place on monitor, IV access, vitals, SpO₂." },
      { step: "Life threats", detail: "Consider ACS, aortic dissection, PE, tension pneumothorax, tamponade, esophageal rupture." },
      { step: "STEMI?", detail: "ST elevation on ECG → activate cath lab / PCI pathway." },
      { step: "Biomarkers", detail: "Serial troponin; if rising → NSTEMI/unstable angina pathway." },
      { step: "Risk stratify", detail: "Use HEART score; low-risk + negative serial troponin may be suitable for outpatient follow-up." },
    ] },
  { id: "syncope", name: "Syncope Evaluation", system: "cardiac",
    summary: "Distinguish benign reflex syncope from high-risk cardiac causes.",
    steps: [
      { step: "History", detail: "Prodrome, exertional onset, palpitations, family history of sudden death — red flags for cardiac cause." },
      { step: "Exam", detail: "Orthostatic vitals, cardiac auscultation for murmurs, carotid exam." },
      { step: "ECG", detail: "Look for arrhythmia, conduction disease, pre-excitation, long QT, Brugada pattern." },
      { step: "Reflex vs cardiac", detail: "Reflex (vasovagal) — situational, with prodrome. Cardiac — exertional, abrupt, structural/electrical disease." },
      { step: "Disposition", detail: "High-risk features (abnormal ECG, heart failure, exertional) → admit/monitor." },
    ] },
  { id: "dizziness", name: "Acute Dizziness / Vertigo (HINTS)", system: "neuro",
    summary: "For continuous vertigo (acute vestibular syndrome), the HINTS exam helps separate peripheral from central causes.",
    steps: [
      { step: "Characterize", detail: "Episodic positional (BPPV) → Dix–Hallpike. Continuous (AVS) → HINTS exam." },
      { step: "Head impulse", detail: "Normal (no corrective saccade) in AVS is concerning for a CENTRAL cause." },
      { step: "Nystagmus", detail: "Direction-changing or vertical nystagmus suggests central." },
      { step: "Test of skew", detail: "Vertical skew on cover-uncover suggests central." },
      { step: "Interpretation", detail: "Any central HINTS finding → urgent neuroimaging (MRI) for posterior stroke." },
    ] },
  { id: "abdomen", name: "Acute Abdominal Pain", system: "gi",
    summary: "Localize by quadrant and identify surgical emergencies early.",
    steps: [
      { step: "Stabilize", detail: "Vitals, IV access; assess for peritonitis (rigidity, rebound, guarding)." },
      { step: "Localize", detail: "RUQ → biliary; epigastric → PUD/pancreas; RLQ → appendicitis; LLQ → diverticulitis; flank → renal." },
      { step: "Special signs", detail: "Murphy's (cholecystitis), McBurney's/Rovsing's/psoas/obturator (appendicitis), CVA tenderness (renal)." },
      { step: "Labs", detail: "CBC, lipase, LFTs, lactate, urinalysis, pregnancy test in people who can be pregnant." },
      { step: "Imaging", detail: "Ultrasound (biliary, pelvic) or CT per suspicion; surgical consult for acute abdomen." },
    ] },
];

export const SYSTEM_LABELS = {
  cardiac: "Cardiac", pulmonary: "Pulmonary", gi: "GI / Abdominal",
  neuro: "Neuro-Vestibular", msk: "Musculoskeletal", heent: "HEENT",
  gu: "Genitourinary", endo: "Endocrine & Systemic",
};
